services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:slim
    container_name: open-webui
    restart: unless-stopped
    networks:
      - athena
    ports:
      - 10003:8080
    volumes:
      - open-webui_data:/app/backend/data
    environment:
      - WEBUI_AUTH_TRUSTED_EMAIL_HEADER=Remote-Email
      - WEBUI_AUTH_TRUSTED_NAME_HEADER=Remote-Name

networks:
  athena:
    external: true 

volumes:
  open-webui_data:
