services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    restart: unless-stopped
    networks:
      - athena
    volumes:
      - ./config:/config
    environment:
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/config/secrets/jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/config/secrets/session_secret
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/config/secrets/storage_encryption_key

networks:
  athena:
    external: true
