services:
  glance:
    image: glanceapp/glance
    container_name: glance
    restart: unless-stopped
    networks:
      - athena
    # ports:
    #   - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/app/config

networks:
  athena:
    external: true