authentication_backend:
  file:
    path: /config/users.yml

access_control:
  default_policy: deny
  rules:
    - domain: "*.abhithube.com"
      policy: one_factor

session:
  cookies:
    - domain: abhithube.com
      authelia_url: https://auth.abhithube.com
      default_redirection_url: https://dashboard.abhithube.com

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt