pages:
  - name: Home
    columns:
      - size: small
        widgets:
          - type: calendar
            first-day-of-week: monday

          - type: rss
            limit: 10
            collapse-after: 3
            cache: 12h
            feeds:
              - url: https://proton.me/blog/feed
                title: The Proton Blog

      - size: full
        widgets:
          - type: hacker-news

          - type: videos
            channels:
              - UCsBjURrPoezykLs9EqgamOA # Fireship
              - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
              - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee

          - type: group
            widgets:
              - type: reddit
                subreddit: selfhosted
                show-thumbnails: true
              - type: reddit
                subreddit: technology
                show-thumbnails: true

      - size: small
        widgets:
          - type: markets
            markets:
              - symbol: AAPL
                name: Apple
              - symbol: BTC-USD
                name: Bitcoin
              - symbol: NVDA
                name: NVIDIA

          - type: releases
            cache: 1d
            repositories:
              - glanceapp/glance